# fly.toml app configuration file generated for sen-sage on 2024-08-03T19:34:07+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sen-sage'
primary_region = 'hkg'

[mounts]
source = "sen_sage_vol"
destination = "/data"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
